Repository PicoPitch/PicoPitch-Backend-Repository, pull requests merged in 2024-07, with the labels that each got.

#3 Ci/1
  .github/workflows/dev_deploy.yml
  .platform/nginx/nginx.conf
  Procfile
  config/response.js
  config/response.status.js
  config/swagger.config.js
  index.js
  package-lock.json
  package.json
  src/controllers/health.controller.js
  src/routes/health.route.js
  webpack.config.js
Labels: feat, ci

#5 [ci/cd]webpack mode 추가
  webpack.config.js
Labels: ci

#7 [CI/CD] npm run build 작동하도록 webpack 수정
  .babelrc
  config/response.js
  package-lock.json
  package.json
  src/index.js
  webpack.config.js
Labels: ci

#8 [CI/CD] npm start, build 둘 다 작동하도록 수정
  package.json
  src/index.js
Labels: ci

#9 [ci]베이스에러 수정
  config/error.js
  config/response.js
  src/index.js
Labels: ci

#10 [ci]package.json의 scripts 모두 정상작동하도록 수정
  package.json
  webpack.config.js
Labels: ci

#12 [Bug] scripts 작동하도록 수정, response 추가, index.js 파일 위치 수정
  config/error.js
  config/response.status.js
  config/swagger.config.js
  index.js
  package-lock.json
  package.json
  webpack.config.js
Labels: bug

#13 yml file revised
  config/db.connect.js
Labels: :bug: bug, :green_heart: ci
