Repository PicoPitch/PicoPitch-Backend-Repository, pull requests merged in 2024-08, with the labels that each got.

#46 Fix/43 깃허브 환경 구성 재설정
  .github/workflows/dev_deploy.yml
  .gitignore
  .idea/.gitignore
  .idea/PicoPitch-Backend.iml
  .idea/aws.xml
  .idea/git_toolbox_blame.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  0731 umc.iml
Labels: :bug: bug

#47 Fix/43 CI/CD 에러 해결
  .github/workflows/dev_deploy.yml
  .platform/nginx/nginx.conf
  Procfile
  config/db.connect.js
  config/response.js
  index.js
  package-lock.json
  package.json
  webpack.config.js
Labels: :bug: bug

#48 Fix/43 Action Workflow 에러 해결
  .github/workflows/dev_deploy.yml
Labels: :bug: bug

#51 feat: resolves feat/10 #50
  index.js
  src/feedback/feedback.controller.js
  src/feedback/feedback.dao.js
  src/feedback/feedback.dto.js
  src/feedback/feedback.model.js
  src/feedback/feedback.route.js
  src/presentation/presentation.dto.js
Labels: :sparkles: feat

#53 fix: feat/10 관련 에러 수정 (resolving #52)
  config/db.connect.js
  index.js
  package-lock.json
  package.json
  src/script/script.controller.js
  src/script/script.dao.js
  src/script/script.dto.js
  src/script/script.model.js
  src/script/script.route.js
Labels: :bug: bug, :sparkles: feat

#54 chore: type_hash 관련 경고 수정 nginx.conf
  .platform/nginx/nginx.conf
Labels: :bug: bug, :green_heart: ci
